# -*- coding: utf-8 -*-
"""miniscrabblefinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vbYtJ1QUGf-YcLb-Uo3GVY3LP7qGVk2_
"""

#Les import random
from random import shuffle
from random import sample

#Fonction de sélection de 3 mots aléatoire dans la liste
def selection_mots(liste_de_mots):
  mots = sample(liste_de_mots, 3) 
  return mots

#Fonction de mélange des lettres
def melange_lettres(mot1, mot2, mot3):
  toutes_lettres = list(mot1 + mot2 + mot3)

  shuffle(toutes_lettres)
  
  lettres_cachees = []
  
  for lettre in toutes_lettres:
    if lettre not in lettres_cachees:
      lettres_cachees.append(lettre)
  return lettres_cachees

#Lancement du jeu
def mini_scrabble():
  nombre_manches = 1
  player_name = input("Entrez votre nom :")
  
  print("Bonjour",player_name,"!")
  
  nombre_points = 0
  
  while nombre_manches <= 3: #Car il y a 3 manches
    print("\nLa manche",nombre_manches,"commence, trouvez les 3 mots cachés !")

#Sélection des 3 mots aléatoires dans la liste

    trois_mots = selection_mots(["nuit", "jour","lune", "haut", "petit", "porte", "facteur", "poche", "casier", "nuage"])
    mot1, mot2, mot3 = trois_mots
    

#Mélange des lettres
    lettres_melanges = melange_lettres(mot1, mot2, mot3)
    print(lettres_melanges)


#Jeu avec les propositions de l'utilisateur
    suggestion = None
    i = 0
    while suggestion not in trois_mots and len(trois_mots) > 0: #Tant que le mot de l'utilisateur n'est pas dans la liste et que la liste n'est pas vide
      print("Il y a des mots à trouver, rentrez s'il vous plait un mot ! Vous pouvez abandonner en entrant 'Quit'")
      suggestion = input()

      if suggestion in trois_mots and i < 3:
        while suggestion in trois_mots and len(trois_mots) > 0:
          #Supprimer le mot deviné de la liste
          trois_mots.remove(suggestion)
          
          nombre_points = nombre_points + 1
          
          print("Gagné, vous avez",nombre_points,"point(s)")
          
          if nombre_points < 3:
            suggestion = input()
          elif nombre_points == 9:
            print("Félicitation",player_name,"tout les mots ont été trouvé !")
      else:
        print("Perdu !")

#Ajout de l'option Quit pour passer à la manche suivante et incrémentation des manches      
      if suggestion == "Quit":
        break
      
    i = i +1

    nombre_manches = nombre_manches + 1

mini_scrabble()